/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 fixed1.glb --transform 
Files: fixed1.glb [1.05MB] > C:\Users\ericx\Desktop\seaforth\fixed1-transformed.glb [85.76KB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/fixed1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.492, 0.914, 0.41]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.551}>
        <mesh geometry={nodes.Cube003_0_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Cube003_0_2.geometry} material={materials['ULT_MAT.001']} />
        <mesh geometry={nodes.Cube003_0_3.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh geometry={nodes.screen.geometry} material={materials.PaletteMaterial003} position={[1.492, 0.914, 0.41]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.551} />
    </group>
  )
}

useGLTF.preload('/fixed1-transformed.glb')
